
package accountinfo;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.0
 * 2017-11-09T17:52:32.862+03:00
 * Generated source version: 3.1.0
 */

@WebFault(name = "NotFoundException", targetNamespace = "http://AccountInfo")
public class MsgNotFoundException extends Exception {
    
    private accountinfo.NotFoundException notFoundException;

    public MsgNotFoundException() {
        super();
    }
    
    public MsgNotFoundException(String message) {
        super(message);
    }
    
    public MsgNotFoundException(String message, Throwable cause) {
        super(message, cause);
    }

    public MsgNotFoundException(String message, accountinfo.NotFoundException notFoundException) {
        super(message);
        this.notFoundException = notFoundException;
    }

    public MsgNotFoundException(String message, accountinfo.NotFoundException notFoundException, Throwable cause) {
        super(message, cause);
        this.notFoundException = notFoundException;
    }

    public accountinfo.NotFoundException getFaultInfo() {
        return this.notFoundException;
    }
}
